//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHED.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AHED.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area treated must be &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_AreaTreated {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_AreaTreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Band width must be &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_BandWidth {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_BandWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boom height must be &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_BoomHeight {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_BoomHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boom width must be &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_BoomWidth {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_BoomWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Cleanup.
        /// </summary>
        internal static string ApplicationInfo_Invalid_Cleanup {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_Cleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop height must be &gt;= 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_CropHeight {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_CropHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth must be &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_Depth {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Diluent.
        /// </summary>
        internal static string ApplicationInfo_Invalid_Diluent {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_Diluent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk size must be &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_DiskSize {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_DiskSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Application Engineering Controls.
        /// </summary>
        internal static string ApplicationInfo_Invalid_Engineering_Controls {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_Engineering_Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Equipment Used.
        /// </summary>
        internal static string ApplicationInfo_Invalid_Equipment_Used {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_Equipment_Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Foliage Density.
        /// </summary>
        internal static string ApplicationInfo_Invalid_Foliage_Density {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_Foliage_Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gound speed must be &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_GroundSpeed {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_GroundSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hopper capacity must be &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_HopperCapacity {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_HopperCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity must be between 0 and 100 percent.
        /// </summary>
        internal static string ApplicationInfo_Invalid_Humidity {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity must be between the min and max.
        /// </summary>
        internal static string ApplicationInfo_Invalid_HumidityBetween {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_HumidityBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity Max must be between 0 and 100 percent.
        /// </summary>
        internal static string ApplicationInfo_Invalid_HumidityMax {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_HumidityMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity Max must be &gt;= Humidity Min.
        /// </summary>
        internal static string ApplicationInfo_Invalid_HumidityMaxMin {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_HumidityMaxMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity Min must be between 0 and 100 percent.
        /// </summary>
        internal static string ApplicationInfo_Invalid_HumidityMin {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_HumidityMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidty Min must be less than or equal to Humidity Max.
        /// </summary>
        internal static string ApplicationInfo_Invalid_HumidityMinMax {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_HumidityMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nozzle pressure must be &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_NozzlePressure {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_NozzlePressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of nozzles must be &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_NumberOfNozzles {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_NumberOfNozzles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Repairs.
        /// </summary>
        internal static string ApplicationInfo_Invalid_Repairs {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_Repairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing between rows must be &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_SpacingBetweenRows {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_SpacingBetweenRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprayer tank volume must be &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_SprayerTankVolume {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_SprayerTankVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swath width must be &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_SwathWidth {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_SwathWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature must be between -50 C and +130 C.
        /// </summary>
        internal static string ApplicationInfo_Invalid_Temperature {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature must be between Temperature Min and Max.
        /// </summary>
        internal static string ApplicationInfo_Invalid_TemperatureBetween {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_TemperatureBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Max must be between -50 C and +130 C.
        /// </summary>
        internal static string ApplicationInfo_Invalid_TemperatureMax {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_TemperatureMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Max must be &gt;= Temperature Min.
        /// </summary>
        internal static string ApplicationInfo_Invalid_TemperatureMaxMin {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_TemperatureMaxMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Min must be between -50 C and +130 C.
        /// </summary>
        internal static string ApplicationInfo_Invalid_TemperatureMin {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_TemperatureMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Min must be &lt; Temperature Max.
        /// </summary>
        internal static string ApplicationInfo_Invalid_TemperatureMinMax {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_TemperatureMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total AI applied must be null or &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_TotalAiApplied {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_TotalAiApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total loads applied must be null or &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_TotalLoadsApplied {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_TotalLoadsApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total spray applied must be null or &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_TotalSprayApplied {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_TotalSprayApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed must be &gt;= 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_WindSpeed {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_WindSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed must be between Wind Speed Min and Max.
        /// </summary>
        internal static string ApplicationInfo_Invalid_WindSpeedBetween {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_WindSpeedBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed max must be &gt;= 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_WindSpeedMax {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_WindSpeedMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed max must be &gt;= Wind speed min.
        /// </summary>
        internal static string ApplicationInfo_Invalid_WindSpeedMaxMin {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_WindSpeedMaxMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed min must be &gt;= 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_WindSpeedMin {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_WindSpeedMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed min must be &lt;= Wind speed max.
        /// </summary>
        internal static string ApplicationInfo_Invalid_WindSpeedMinMax {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_WindSpeedMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\AHEDDatabase\.
        /// </summary>
        internal static string Local_Database_Path {
            get {
                return ResourceManager.GetString("Local_Database_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Cleanup.
        /// </summary>
        internal static string MixingInfo_Invalid_Cleanup {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_Cleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Diluent.
        /// </summary>
        internal static string MixingInfo_Invalid_Diluent {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_Diluent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Equipment Loaded.
        /// </summary>
        internal static string MixingInfo_Invalid_Equipment_Loaded {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_Equipment_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final spray volume mixed must be &gt; 0.
        /// </summary>
        internal static string MixingInfo_Invalid_FinalSprayVolumeMixed {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_FinalSprayVolumeMixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hopper capacity must be &gt; 0.
        /// </summary>
        internal static string MixingInfo_Invalid_HopperCapacity {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_HopperCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity must be between 0 and 100 percent.
        /// </summary>
        internal static string MixingInfo_Invalid_Humidity {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity must be between the min and max.
        /// </summary>
        internal static string MixingInfo_Invalid_HumidityBetween {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_HumidityBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity Max must be between 0 and 100 percent.
        /// </summary>
        internal static string MixingInfo_Invalid_HumidityMax {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_HumidityMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidty Max must be greater than or equal to Humidity Min.
        /// </summary>
        internal static string MixingInfo_Invalid_HumidityMaxMin {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_HumidityMaxMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity Min must be between 0 and 100 percent.
        /// </summary>
        internal static string MixingInfo_Invalid_HumidityMin {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_HumidityMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidty Min must be less than or equal to Humidity Max.
        /// </summary>
        internal static string MixingInfo_Invalid_HumidityMinMax {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_HumidityMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Mixing/Loading Engineering Controls.
        /// </summary>
        internal static string MixingInfo_Invalid_MixLoad_Eng_Controls {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_MixLoad_Eng_Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premix tank capacity must be &gt; 0.
        /// </summary>
        internal static string MixingInfo_Invalid_PremixTankCapacity {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_PremixTankCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Repairs.
        /// </summary>
        internal static string MixingInfo_Invalid_Repairs {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_Repairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Mixing Setup Equipment.
        /// </summary>
        internal static string MixingInfo_Invalid_Setup_Equipment {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_Setup_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprayer tank capacity must be &gt; 0.
        /// </summary>
        internal static string MixingInfo_Invalid_SprayerTankCapacity {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_SprayerTankCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Min must be between -50 C and +130 C, and between Temperature Min and  Temperature Max.
        /// </summary>
        internal static string MixingInfo_Invalid_Temperature {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature must be between Temperature Min and Max.
        /// </summary>
        internal static string MixingInfo_Invalid_TemperatureBetween {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_TemperatureBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Max must be between -50 C and +130 C.
        /// </summary>
        internal static string MixingInfo_Invalid_TemperatureMax {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_TemperatureMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Max must be &gt;= Temperature Min.
        /// </summary>
        internal static string MixingInfo_Invalid_TemperatureMaxMin {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_TemperatureMaxMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Min must be between -50 C and +130 C.
        /// </summary>
        internal static string MixingInfo_Invalid_TemperatureMin {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_TemperatureMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Min must be &lt;= Temperature Max.
        /// </summary>
        internal static string MixingInfo_Invalid_TemperatureMinMax {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_TemperatureMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Loads Mixed must be empty, or a positive number..
        /// </summary>
        internal static string MixingInfo_Invalid_Total_Loads_Mixed {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_Total_Loads_Mixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total AI mixed must be &gt; 0.
        /// </summary>
        internal static string MixingInfo_Invalid_TotalAiMixed {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_TotalAiMixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Speed must be between 0 and 100 mph, and between Wind MIn and Wind Max.
        /// </summary>
        internal static string MixingInfo_Invalid_WindSpeed {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_WindSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed must be between Wind Speed Min and Max.
        /// </summary>
        internal static string MixingInfo_Invalid_WindSpeedBetween {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_WindSpeedBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Max must be between 0 and 100 mph, and greater than or equal to Wind Min.
        /// </summary>
        internal static string MixingInfo_Invalid_WindSpeedMax {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_WindSpeedMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed max must be &gt;= Wind speed min.
        /// </summary>
        internal static string MixingInfo_Invalid_WindSpeedMaxMin {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_WindSpeedMaxMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Min must be between 0 and 100 mph, and less than or equal to Wind Max.
        /// </summary>
        internal static string MixingInfo_Invalid_WindSpeedMin {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_WindSpeedMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed min must be &lt;= Wind speed max.
        /// </summary>
        internal static string MixingInfo_Invalid_WindSpeedMinMax {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_WindSpeedMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Action of Pesticide.
        /// </summary>
        internal static string ProductInfo_Invalid_Action_of_Pesticide {
            get {
                return ResourceManager.GetString("ProductInfo_Invalid_Action_of_Pesticide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Mass per Volume must be empty or &gt; 0.
        /// </summary>
        internal static string ProductInfo_Invalid_AI_Mass_per_Volume {
            get {
                return ResourceManager.GetString("ProductInfo_Invalid_AI_Mass_per_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Formulation.
        /// </summary>
        internal static string ProductInfo_Invalid_Formulation {
            get {
                return ResourceManager.GetString("ProductInfo_Invalid_Formulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Package.
        /// </summary>
        internal static string ProductInfo_Invalid_Package {
            get {
                return ResourceManager.GetString("ProductInfo_Invalid_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Volume must be empty or &gt; 0.
        /// </summary>
        internal static string ProductInfo_Invalid_Package_Volume {
            get {
                return ResourceManager.GetString("ProductInfo_Invalid_Package_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Weight must be empty or &gt; 0.
        /// </summary>
        internal static string ProductInfo_Invalid_Package_Weight {
            get {
                return ResourceManager.GetString("ProductInfo_Invalid_Package_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage AI by Weight must be empty or &gt; 0.
        /// </summary>
        internal static string ProductInfo_Invalid_Percentage_AI_by_Weight {
            get {
                return ResourceManager.GetString("ProductInfo_Invalid_Percentage_AI_by_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vapor Pressure must be empty or &gt; 0.
        /// </summary>
        internal static string ProductInfo_Invalid_Vapor_Pressure {
            get {
                return ResourceManager.GetString("ProductInfo_Invalid_Vapor_Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vapor Pressure at C must be empty or &gt; 0.
        /// </summary>
        internal static string ProductInfo_Invalid_Vapor_Pressure_at_C {
            get {
                return ResourceManager.GetString("ProductInfo_Invalid_Vapor_Pressure_at_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datamanagerservicesite/DataManager.svc.
        /// </summary>
        internal static string Server_DataManager_EndPoint {
            get {
                return ResourceManager.GetString("Server_DataManager_EndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 54.225.65.147.
        /// </summary>
        internal static string Server_IP {
            get {
                return ResourceManager.GetString("Server_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http:.
        /// </summary>
        internal static string Server_Transport {
            get {
                return ResourceManager.GetString("Server_Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age must be either empty, or between 10 and 127 (years).
        /// </summary>
        internal static string WorkerInfo_Invalid_Age {
            get {
                return ResourceManager.GetString("WorkerInfo_Invalid_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio Monitoring must either be empty, or a valid description.
        /// </summary>
        internal static string WorkerInfo_Invalid_Biomonitoring {
            get {
                return ResourceManager.GetString("WorkerInfo_Invalid_Biomonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Country.
        /// </summary>
        internal static string WorkerInfo_Invalid_Country {
            get {
                return ResourceManager.GetString("WorkerInfo_Invalid_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County / Locale must be either empty, or valid for the State or Province specified.
        /// </summary>
        internal static string WorkerInfo_Invalid_County_Locale {
            get {
                return ResourceManager.GetString("WorkerInfo_Invalid_County_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Employment.
        /// </summary>
        internal static string WorkerInfo_Invalid_Employment {
            get {
                return ResourceManager.GetString("WorkerInfo_Invalid_Employment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender must be either empty, or &quot;Male&quot;, or &quot;Female&quot;.
        /// </summary>
        internal static string WorkerInfo_Invalid_Gender {
            get {
                return ResourceManager.GetString("WorkerInfo_Invalid_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height must be either empty, or between {0} and {1} ({2}).
        /// </summary>
        internal static string WorkerInfo_Invalid_Height {
            get {
                return ResourceManager.GetString("WorkerInfo_Invalid_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replicate Date must be provided.
        /// </summary>
        internal static string WorkerInfo_Invalid_Replicate_Date {
            get {
                return ResourceManager.GetString("WorkerInfo_Invalid_Replicate_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Season.
        /// </summary>
        internal static string WorkerInfo_Invalid_Season {
            get {
                return ResourceManager.GetString("WorkerInfo_Invalid_Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Site.
        /// </summary>
        internal static string WorkerInfo_Invalid_Site {
            get {
                return ResourceManager.GetString("WorkerInfo_Invalid_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State or Province must be either empty, or valid for the Country specified.
        /// </summary>
        internal static string WorkerInfo_Invalid_State_Province {
            get {
                return ResourceManager.GetString("WorkerInfo_Invalid_State_Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Task.
        /// </summary>
        internal static string WorkerInfo_Invalid_Task {
            get {
                return ResourceManager.GetString("WorkerInfo_Invalid_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town must be either empty, or valid for the county / locale specified.
        /// </summary>
        internal static string WorkerInfo_Invalid_Town {
            get {
                return ResourceManager.GetString("WorkerInfo_Invalid_Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight must be either empty, or between {0} and {1} ({2}).
        /// </summary>
        internal static string WorkerInfo_Invalid_Weight {
            get {
                return ResourceManager.GetString("WorkerInfo_Invalid_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years of Experience must be either empty, or a positive integer.
        /// </summary>
        internal static string WorkerInfo_Invalid_Years_Experience {
            get {
                return ResourceManager.GetString("WorkerInfo_Invalid_Years_Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker ID must be provided.
        /// </summary>
        internal static string WorkerInfo_Missing_Id {
            get {
                return ResourceManager.GetString("WorkerInfo_Missing_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replicate ID must be provided.
        /// </summary>
        internal static string WorkerInfo_Missing_Replicate_Id {
            get {
                return ResourceManager.GetString("WorkerInfo_Missing_Replicate_Id", resourceCulture);
            }
        }
    }
}
