//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHED.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AHED.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytic Tools.
        /// </summary>
        internal static string AhedViewModel_Command_AnalyticTools {
            get {
                return ResourceManager.GetString("AhedViewModel_Command_AnalyticTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Reports.
        /// </summary>
        internal static string AhedViewModel_Command_DataReports {
            get {
                return ResourceManager.GetString("AhedViewModel_Command_DataReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Databases.
        /// </summary>
        internal static string AhedViewModel_Command_LocalDatabases {
            get {
                return ResourceManager.GetString("AhedViewModel_Command_LocalDatabases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Databases.
        /// </summary>
        internal static string AhedViewModel_Command_ServerDatabases {
            get {
                return ResourceManager.GetString("AhedViewModel_Command_ServerDatabases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AHED v2.0.2.
        /// </summary>
        internal static string AhedViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AhedViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Fortifications.
        /// </summary>
        internal static string AllFieldForitifications_Display_Name {
            get {
                return ResourceManager.GetString("AllFieldForitifications_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Entries.
        /// </summary>
        internal static string AllFieldFortEntries_Display_Name {
            get {
                return ResourceManager.GetString("AllFieldFortEntries_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicable Monitoring Unit Ids.
        /// </summary>
        internal static string AllMonitoringUnitIds_Display_Name {
            get {
                return ResourceManager.GetString("AllMonitoringUnitIds_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outer Measurements.
        /// </summary>
        internal static string AllOuterMeasurements_Display_Name {
            get {
                return ResourceManager.GetString("AllOuterMeasurements_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPE Layers.
        /// </summary>
        internal static string AllPpeLayers_Display_Name {
            get {
                return ResourceManager.GetString("AllPpeLayers_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Entries.
        /// </summary>
        internal static string AllViewModel_Display_Name {
            get {
                return ResourceManager.GetString("AllViewModel_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update this ApplicationInfo because validation errors exist..
        /// </summary>
        internal static string ApplicationInfo_Exception_Cannot_Update {
            get {
                return ResourceManager.GetString("ApplicationInfo_Exception_Cannot_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area treated must be &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_AreaTreated {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_AreaTreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Band width must be &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_BandWidth {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_BandWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boom height must be &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_BoomHeight {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_BoomHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boom width must be &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_BoomWidth {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_BoomWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Cleanup.
        /// </summary>
        internal static string ApplicationInfo_Invalid_Cleanup {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_Cleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop height must be &gt;= 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_CropHeight {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_CropHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth must be &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_Depth {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Diluent.
        /// </summary>
        internal static string ApplicationInfo_Invalid_Diluent {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_Diluent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk size must be &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_DiskSize {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_DiskSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Application Engineering Controls.
        /// </summary>
        internal static string ApplicationInfo_Invalid_Engineering_Controls {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_Engineering_Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Equipment Used.
        /// </summary>
        internal static string ApplicationInfo_Invalid_Equipment_Used {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_Equipment_Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Foliage Density.
        /// </summary>
        internal static string ApplicationInfo_Invalid_Foliage_Density {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_Foliage_Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gound speed must be &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_GroundSpeed {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_GroundSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hopper capacity must be &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_HopperCapacity {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_HopperCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity must be between 0 and 100 percent.
        /// </summary>
        internal static string ApplicationInfo_Invalid_Humidity {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity must be between the min and max.
        /// </summary>
        internal static string ApplicationInfo_Invalid_HumidityBetween {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_HumidityBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity Max must be between 0 and 100 percent.
        /// </summary>
        internal static string ApplicationInfo_Invalid_HumidityMax {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_HumidityMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity Max must be &gt;= Humidity Min.
        /// </summary>
        internal static string ApplicationInfo_Invalid_HumidityMaxMin {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_HumidityMaxMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity Min must be between 0 and 100 percent.
        /// </summary>
        internal static string ApplicationInfo_Invalid_HumidityMin {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_HumidityMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidty Min must be less than or equal to Humidity Max.
        /// </summary>
        internal static string ApplicationInfo_Invalid_HumidityMinMax {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_HumidityMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nozzle pressure must be &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_NozzlePressure {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_NozzlePressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of nozzles must be &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_NumberOfNozzles {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_NumberOfNozzles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Repairs.
        /// </summary>
        internal static string ApplicationInfo_Invalid_Repairs {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_Repairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing between rows must be &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_SpacingBetweenRows {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_SpacingBetweenRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprayer tank volume must be &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_SprayerTankVolume {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_SprayerTankVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swath width must be &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_SwathWidth {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_SwathWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature must be between -50 C and +130 C.
        /// </summary>
        internal static string ApplicationInfo_Invalid_Temperature {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature must be between Temperature Min and Max.
        /// </summary>
        internal static string ApplicationInfo_Invalid_TemperatureBetween {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_TemperatureBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Max must be between -50 C and +130 C.
        /// </summary>
        internal static string ApplicationInfo_Invalid_TemperatureMax {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_TemperatureMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Max must be &gt;= Temperature Min.
        /// </summary>
        internal static string ApplicationInfo_Invalid_TemperatureMaxMin {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_TemperatureMaxMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Min must be between -50 C and +130 C.
        /// </summary>
        internal static string ApplicationInfo_Invalid_TemperatureMin {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_TemperatureMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Min must be &lt; Temperature Max.
        /// </summary>
        internal static string ApplicationInfo_Invalid_TemperatureMinMax {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_TemperatureMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total AI applied must be null or &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_TotalAiApplied {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_TotalAiApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total loads applied must be null or &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_TotalLoadsApplied {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_TotalLoadsApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total spray applied must be null or &gt; 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_TotalSprayApplied {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_TotalSprayApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed must be &gt;= 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_WindSpeed {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_WindSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed must be between Wind Speed Min and Max.
        /// </summary>
        internal static string ApplicationInfo_Invalid_WindSpeedBetween {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_WindSpeedBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed max must be &gt;= 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_WindSpeedMax {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_WindSpeedMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed max must be &gt;= Wind speed min.
        /// </summary>
        internal static string ApplicationInfo_Invalid_WindSpeedMaxMin {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_WindSpeedMaxMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed min must be &gt;= 0.
        /// </summary>
        internal static string ApplicationInfo_Invalid_WindSpeedMin {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_WindSpeedMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed min must be &lt;= Wind speed max.
        /// </summary>
        internal static string ApplicationInfo_Invalid_WindSpeedMinMax {
            get {
                return ResourceManager.GetString("ApplicationInfo_Invalid_WindSpeedMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AHED Administrator.
        /// </summary>
        internal static string AuthorizationGroup_AhedAdministrator {
            get {
                return ResourceManager.GetString("AuthorizationGroup_AhedAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AHED Data Entry.
        /// </summary>
        internal static string AuthorizationGroup_AhedDataEntry {
            get {
                return ResourceManager.GetString("AuthorizationGroup_AhedDataEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AHED Quality Assurance.
        /// </summary>
        internal static string AuthorizationGroup_AhedQualityAssurance {
            get {
                return ResourceManager.GetString("AuthorizationGroup_AhedQualityAssurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AHED User.
        /// </summary>
        internal static string AuthorizationGroup_AhedUser {
            get {
                return ResourceManager.GetString("AuthorizationGroup_AhedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid date must be provided, and it must be after the latest Changes Date in the containing Database..
        /// </summary>
        internal static string ChangeLogModel_Invalid_DateChanged {
            get {
                return ResourceManager.GetString("ChangeLogModel_Invalid_DateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be the Local User, or match an Identity on the AHED Server..
        /// </summary>
        internal static string ChangeLogModel_Invalid_Identity {
            get {
                return ResourceManager.GetString("ChangeLogModel_Invalid_Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have a value greater than or equal to the VersionMajor of the containing Database..
        /// </summary>
        internal static string ChangeLogModel_Invalid_VersionMajor {
            get {
                return ResourceManager.GetString("ChangeLogModel_Invalid_VersionMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have a value greater than the VersionMinor of the containing Database..
        /// </summary>
        internal static string ChangeLogModel_Invalid_VersionMinor {
            get {
                return ResourceManager.GetString("ChangeLogModel_Invalid_VersionMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.xmlsoap.org/claims/Group.
        /// </summary>
        internal static string Claim_Group {
            get {
                return ResourceManager.GetString("Claim_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment cannot be null, but can be empty..
        /// </summary>
        internal static string Comment_Invalid_Comment {
            get {
                return ResourceManager.GetString("Comment_Invalid_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string CommentViewModel_Display_Name {
            get {
                return ResourceManager.GetString("CommentViewModel_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save this comment because validation errors exist..
        /// </summary>
        internal static string CommentViewModel_Exception_Cannot_Save {
            get {
                return ResourceManager.GetString("CommentViewModel_Exception_Cannot_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        internal static string CultureName {
            get {
                return ResourceManager.GetString("CultureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid date must be provided..
        /// </summary>
        internal static string DatabaseModel_Invalid_DateCreated {
            get {
                return ResourceManager.GetString("DatabaseModel_Invalid_DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid date must be provided, and it cannot be before Date Created..
        /// </summary>
        internal static string DatabaseModel_Invalid_DateLastModified {
            get {
                return ResourceManager.GetString("DatabaseModel_Invalid_DateLastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is a required field..
        /// </summary>
        internal static string DatabaseModel_Invalid_Name {
            get {
                return ResourceManager.GetString("DatabaseModel_Invalid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have a value greater than or equal to 1..
        /// </summary>
        internal static string DatabaseModel_Invalid_VersionMajor {
            get {
                return ResourceManager.GetString("DatabaseModel_Invalid_VersionMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have a value greater than or equal to 0..
        /// </summary>
        internal static string DatabaseModel_Invalid_VersionMinor {
            get {
                return ResourceManager.GetString("DatabaseModel_Invalid_VersionMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Access Entry.
        /// </summary>
        internal static string DatabaseViewModel_Command_CreateNewAccessEntry {
            get {
                return ResourceManager.GetString("DatabaseViewModel_Command_CreateNewAccessEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Study.
        /// </summary>
        internal static string DatabaseViewModel_Command_CreateNewStudy {
            get {
                return ResourceManager.GetString("DatabaseViewModel_Command_CreateNewStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected Access Entries.
        /// </summary>
        internal static string DatabaseViewModel_Command_Delete_Selected_AccessEntries {
            get {
                return ResourceManager.GetString("DatabaseViewModel_Command_Delete_Selected_AccessEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected Studies.
        /// </summary>
        internal static string DatabaseViewModel_Command_Delete_Selected_Studies {
            get {
                return ResourceManager.GetString("DatabaseViewModel_Command_Delete_Selected_Studies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Table.
        /// </summary>
        internal static string DatabaseViewModel_Command_Show_StaticTable {
            get {
                return ResourceManager.GetString("DatabaseViewModel_Command_Show_StaticTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Entries.
        /// </summary>
        internal static string DatabaseViewModel_Command_ShowAllAccessEntries {
            get {
                return ResourceManager.GetString("DatabaseViewModel_Command_ShowAllAccessEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Log.
        /// </summary>
        internal static string DatabaseViewModel_Command_ShowAllChangeLogEntries {
            get {
                return ResourceManager.GetString("DatabaseViewModel_Command_ShowAllChangeLogEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studies.
        /// </summary>
        internal static string DatabaseViewModel_Command_ShowAllStudies {
            get {
                return ResourceManager.GetString("DatabaseViewModel_Command_ShowAllStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Info.
        /// </summary>
        internal static string DataViewModel_Command_ApplicationInfo {
            get {
                return ResourceManager.GetString("DataViewModel_Command_ApplicationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Fortifications.
        /// </summary>
        internal static string DataViewModel_Command_FieldFortifications {
            get {
                return ResourceManager.GetString("DataViewModel_Command_FieldFortifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurements.
        /// </summary>
        internal static string DataViewModel_Command_Measurements {
            get {
                return ResourceManager.GetString("DataViewModel_Command_Measurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixing Info.
        /// </summary>
        internal static string DataViewModel_Command_MixingInfo {
            get {
                return ResourceManager.GetString("DataViewModel_Command_MixingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Info.
        /// </summary>
        internal static string DataViewModel_Command_ProductInfo {
            get {
                return ResourceManager.GetString("DataViewModel_Command_ProductInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker Info.
        /// </summary>
        internal static string DataViewModel_Command_WorkerInfo {
            get {
                return ResourceManager.GetString("DataViewModel_Command_WorkerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid Dosimeter Description must be chosen..
        /// </summary>
        internal static string DosimeterMeasurement_Invalid_Dosimeter_Description {
            get {
                return ResourceManager.GetString("DosimeterMeasurement_Invalid_Dosimeter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid Dosimeter Group must be chosen..
        /// </summary>
        internal static string DosimeterMeasurement_Invalid_Group {
            get {
                return ResourceManager.GetString("DosimeterMeasurement_Invalid_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Outer Measurement.
        /// </summary>
        internal static string DosimeterMeasurementViewModel_Command_CreateNewOuterMeasurement {
            get {
                return ResourceManager.GetString("DosimeterMeasurementViewModel_Command_CreateNewOuterMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New PPE Layer.
        /// </summary>
        internal static string DosimeterMeasurementViewModel_Command_CreateNewPpeLayer {
            get {
                return ResourceManager.GetString("DosimeterMeasurementViewModel_Command_CreateNewPpeLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected Outer Measurements.
        /// </summary>
        internal static string DosimeterMeasurementViewModel_Command_Delete_Selected_OuterMeasurements {
            get {
                return ResourceManager.GetString("DosimeterMeasurementViewModel_Command_Delete_Selected_OuterMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected PPE Layers.
        /// </summary>
        internal static string DosimeterMeasurementViewModel_Command_Delete_Selected_PpeLayers {
            get {
                return ResourceManager.GetString("DosimeterMeasurementViewModel_Command_Delete_Selected_PpeLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save this dosimeter measurement because validation errors exist..
        /// </summary>
        internal static string DosimeterMeasurementViewModel_Exception_Cannot_Save {
            get {
                return ResourceManager.GetString("DosimeterMeasurementViewModel_Exception_Cannot_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be present, and unique in this Field Fortification..
        /// </summary>
        internal static string FieldFortEntry_Description {
            get {
                return ResourceManager.GetString("FieldFortEntry_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field fortification entries must have unique descriptions..
        /// </summary>
        internal static string FieldFortEntry_Description_Unique {
            get {
                return ResourceManager.GetString("FieldFortEntry_Description_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update this FieldFortEntry because validation errors exist..
        /// </summary>
        internal static string FieldFortEntry_Exception_Cannot_Update {
            get {
                return ResourceManager.GetString("FieldFortEntry_Exception_Cannot_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input fortification adjustment factor must be present, and greater than 0..
        /// </summary>
        internal static string FieldFortEntry_Fortification_Adjustment {
            get {
                return ResourceManager.GetString("FieldFortEntry_Fortification_Adjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input fortification level must be present, and greater than 0..
        /// </summary>
        internal static string FieldFortEntry_Fortification_Level {
            get {
                return ResourceManager.GetString("FieldFortEntry_Fortification_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field fortification entry must be valid before it can be saved..
        /// </summary>
        internal static string FieldFortEntryVm_Exception_CannotSave {
            get {
                return ResourceManager.GetString("FieldFortEntryVm_Exception_CannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosimeter description must be one of the Field Fortification dosimeter descriptions..
        /// </summary>
        internal static string FieldFortification_Dosimeter_Description {
            get {
                return ResourceManager.GetString("FieldFortification_Dosimeter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Id must be provided and unique..
        /// </summary>
        internal static string FieldFortification_Event_Id {
            get {
                return ResourceManager.GetString("FieldFortification_Event_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update this Field Fortification because validation errors exist..
        /// </summary>
        internal static string FieldFortification_Exception_Cannot_Udpate {
            get {
                return ResourceManager.GetString("FieldFortification_Exception_Cannot_Udpate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Entry.
        /// </summary>
        internal static string FieldFortificationViewModel_Command_CreateNewEntry {
            get {
                return ResourceManager.GetString("FieldFortificationViewModel_Command_CreateNewEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Monitoring Unit Id.
        /// </summary>
        internal static string FieldFortificationViewModel_Command_CreateNewMonitoringUnitId {
            get {
                return ResourceManager.GetString("FieldFortificationViewModel_Command_CreateNewMonitoringUnitId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Entries.
        /// </summary>
        internal static string FieldFortificationViewModel_Command_Delete_Selected_Entries {
            get {
                return ResourceManager.GetString("FieldFortificationViewModel_Command_Delete_Selected_Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Ids.
        /// </summary>
        internal static string FieldFortificationViewModel_Command_Delete_Selected_MonitoringUnitIds {
            get {
                return ResourceManager.GetString("FieldFortificationViewModel_Command_Delete_Selected_MonitoringUnitIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all Entries.
        /// </summary>
        internal static string FieldFortificationViewModel_Command_ViewAllEntries {
            get {
                return ResourceManager.GetString("FieldFortificationViewModel_Command_ViewAllEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all Monitoring Unit Ids.
        /// </summary>
        internal static string FieldFortificationViewModel_Command_ViewAllMonitoringUnitIds {
            get {
                return ResourceManager.GetString("FieldFortificationViewModel_Command_ViewAllMonitoringUnitIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\AHEDDatabase\.
        /// </summary>
        internal static string Local_Database_Path {
            get {
                return ResourceManager.GetString("Local_Database_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid Input Dosimeter Matrix must be chosen..
        /// </summary>
        internal static string Measurement_Invalid_Input_Dosimeter_Matrix {
            get {
                return ResourceManager.GetString("Measurement_Invalid_Input_Dosimeter_Matrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input LOD must be &gt; 0.
        /// </summary>
        internal static string Measurement_Invalid_Input_Lod {
            get {
                return ResourceManager.GetString("Measurement_Invalid_Input_Lod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOQ must be &gt; 0.
        /// </summary>
        internal static string Measurement_Invalid_Input_Loq {
            get {
                return ResourceManager.GetString("Measurement_Invalid_Input_Loq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Residue must be &gt; 0, LOQ, or LOQ.
        /// </summary>
        internal static string Measurement_Invalid_Input_Residue {
            get {
                return ResourceManager.GetString("Measurement_Invalid_Input_Residue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size must be &gt; 0.
        /// </summary>
        internal static string Measurement_Invalid_Size {
            get {
                return ResourceManager.GetString("Measurement_Invalid_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update this measurement because validation errors exist..
        /// </summary>
        internal static string MeasurementViewModel_Exception_Cannot_Update {
            get {
                return ResourceManager.GetString("MeasurementViewModel_Exception_Cannot_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update this MixingInfo because validation errors exist..
        /// </summary>
        internal static string MixingInfo_Exception_Cannot_Update {
            get {
                return ResourceManager.GetString("MixingInfo_Exception_Cannot_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Cleanup.
        /// </summary>
        internal static string MixingInfo_Invalid_Cleanup {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_Cleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Diluent.
        /// </summary>
        internal static string MixingInfo_Invalid_Diluent {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_Diluent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Equipment Loaded.
        /// </summary>
        internal static string MixingInfo_Invalid_Equipment_Loaded {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_Equipment_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final spray volume mixed must be &gt; 0.
        /// </summary>
        internal static string MixingInfo_Invalid_FinalSprayVolumeMixed {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_FinalSprayVolumeMixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hopper capacity must be &gt; 0.
        /// </summary>
        internal static string MixingInfo_Invalid_HopperCapacity {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_HopperCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity must be between 0 and 100 percent.
        /// </summary>
        internal static string MixingInfo_Invalid_Humidity {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity must be between the min and max.
        /// </summary>
        internal static string MixingInfo_Invalid_HumidityBetween {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_HumidityBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity Max must be between 0 and 100 percent.
        /// </summary>
        internal static string MixingInfo_Invalid_HumidityMax {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_HumidityMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidty Max must be greater than or equal to Humidity Min.
        /// </summary>
        internal static string MixingInfo_Invalid_HumidityMaxMin {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_HumidityMaxMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity Min must be between 0 and 100 percent.
        /// </summary>
        internal static string MixingInfo_Invalid_HumidityMin {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_HumidityMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidty Min must be less than or equal to Humidity Max.
        /// </summary>
        internal static string MixingInfo_Invalid_HumidityMinMax {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_HumidityMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Mixing/Loading Engineering Controls.
        /// </summary>
        internal static string MixingInfo_Invalid_MixLoad_Eng_Controls {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_MixLoad_Eng_Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premix tank capacity must be &gt; 0.
        /// </summary>
        internal static string MixingInfo_Invalid_PremixTankCapacity {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_PremixTankCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Repairs.
        /// </summary>
        internal static string MixingInfo_Invalid_Repairs {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_Repairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Mixing Setup Equipment.
        /// </summary>
        internal static string MixingInfo_Invalid_Setup_Equipment {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_Setup_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprayer tank capacity must be &gt; 0.
        /// </summary>
        internal static string MixingInfo_Invalid_SprayerTankCapacity {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_SprayerTankCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Min must be between -50 C and +130 C, and between Temperature Min and  Temperature Max.
        /// </summary>
        internal static string MixingInfo_Invalid_Temperature {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature must be between Temperature Min and Max.
        /// </summary>
        internal static string MixingInfo_Invalid_TemperatureBetween {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_TemperatureBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Max must be between -50 C and +130 C.
        /// </summary>
        internal static string MixingInfo_Invalid_TemperatureMax {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_TemperatureMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Max must be &gt;= Temperature Min.
        /// </summary>
        internal static string MixingInfo_Invalid_TemperatureMaxMin {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_TemperatureMaxMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Min must be between -50 C and +130 C.
        /// </summary>
        internal static string MixingInfo_Invalid_TemperatureMin {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_TemperatureMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Min must be &lt;= Temperature Max.
        /// </summary>
        internal static string MixingInfo_Invalid_TemperatureMinMax {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_TemperatureMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Loads Mixed must be empty, or a positive number..
        /// </summary>
        internal static string MixingInfo_Invalid_Total_Loads_Mixed {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_Total_Loads_Mixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total AI mixed must be &gt; 0.
        /// </summary>
        internal static string MixingInfo_Invalid_TotalAiMixed {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_TotalAiMixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Speed must be between 0 and 100 mph, and between Wind MIn and Wind Max.
        /// </summary>
        internal static string MixingInfo_Invalid_WindSpeed {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_WindSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed must be between Wind Speed Min and Max.
        /// </summary>
        internal static string MixingInfo_Invalid_WindSpeedBetween {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_WindSpeedBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Max must be between 0 and 100 mph, and greater than or equal to Wind Min.
        /// </summary>
        internal static string MixingInfo_Invalid_WindSpeedMax {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_WindSpeedMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed max must be &gt;= Wind speed min.
        /// </summary>
        internal static string MixingInfo_Invalid_WindSpeedMaxMin {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_WindSpeedMaxMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Min must be between 0 and 100 mph, and less than or equal to Wind Max.
        /// </summary>
        internal static string MixingInfo_Invalid_WindSpeedMin {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_WindSpeedMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed min must be &lt;= Wind speed max.
        /// </summary>
        internal static string MixingInfo_Invalid_WindSpeedMinMax {
            get {
                return ResourceManager.GetString("MixingInfo_Invalid_WindSpeedMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save this model&apos;s value because validation errors exist..
        /// </summary>
        internal static string Model_Exception_Cannot_Update {
            get {
                return ResourceManager.GetString("Model_Exception_Cannot_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |.
        /// </summary>
        internal static string MonitoringUnit_Id_Separator {
            get {
                return ResourceManager.GetString("MonitoringUnit_Id_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update this MonitoringUnitId because validation errors exist..
        /// </summary>
        internal static string MonitoringUnitId_Exception_Cannot_Upate {
            get {
                return ResourceManager.GetString("MonitoringUnitId_Exception_Cannot_Upate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replicate Id must be provided..
        /// </summary>
        internal static string MonitoringUnitId_Replicate_Id {
            get {
                return ResourceManager.GetString("MonitoringUnitId_Replicate_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker Id must be provided..
        /// </summary>
        internal static string MonitoringUnitId_Worker_Id {
            get {
                return ResourceManager.GetString("MonitoringUnitId_Worker_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Measurement.
        /// </summary>
        internal static string MonitoringUnitMeasurementViewModel_Command_CreateNewMeasurement {
            get {
                return ResourceManager.GetString("MonitoringUnitMeasurementViewModel_Command_CreateNewMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected Measurements.
        /// </summary>
        internal static string MonitoringUnitMeasurementViewModel_Command_DeleteMeasurements {
            get {
                return ResourceManager.GetString("MonitoringUnitMeasurementViewModel_Command_DeleteMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Comment.
        /// </summary>
        internal static string MonitoringUnitViewModel_Command_CreateNewComment {
            get {
                return ResourceManager.GetString("MonitoringUnitViewModel_Command_CreateNewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected Comments.
        /// </summary>
        internal static string MonitoringUnitViewModel_Command_DeleteSelectedComments {
            get {
                return ResourceManager.GetString("MonitoringUnitViewModel_Command_DeleteSelectedComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save this monitoring unit because validation errors exist..
        /// </summary>
        internal static string MonitoringUnitViewModel_Exception_Cannot_Save {
            get {
                return ResourceManager.GetString("MonitoringUnitViewModel_Exception_Cannot_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update this PPE Layer because validation errors exist..
        /// </summary>
        internal static string PpeLayer_Exception_Cannot_Update {
            get {
                return ResourceManager.GetString("PpeLayer_Exception_Cannot_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Action of Pesticide.
        /// </summary>
        internal static string ProductInfo_Invalid_Action_of_Pesticide {
            get {
                return ResourceManager.GetString("ProductInfo_Invalid_Action_of_Pesticide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Mass per Volume must be empty or &gt; 0.
        /// </summary>
        internal static string ProductInfo_Invalid_AI_Mass_per_Volume {
            get {
                return ResourceManager.GetString("ProductInfo_Invalid_AI_Mass_per_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Formulation.
        /// </summary>
        internal static string ProductInfo_Invalid_Formulation {
            get {
                return ResourceManager.GetString("ProductInfo_Invalid_Formulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Package.
        /// </summary>
        internal static string ProductInfo_Invalid_Package {
            get {
                return ResourceManager.GetString("ProductInfo_Invalid_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Volume must be empty or &gt; 0.
        /// </summary>
        internal static string ProductInfo_Invalid_Package_Volume {
            get {
                return ResourceManager.GetString("ProductInfo_Invalid_Package_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Weight must be empty or &gt; 0.
        /// </summary>
        internal static string ProductInfo_Invalid_Package_Weight {
            get {
                return ResourceManager.GetString("ProductInfo_Invalid_Package_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage AI by Weight must be empty or &gt; 0.
        /// </summary>
        internal static string ProductInfo_Invalid_Percentage_AI_by_Weight {
            get {
                return ResourceManager.GetString("ProductInfo_Invalid_Percentage_AI_by_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vapor Pressure must be empty or &gt; 0.
        /// </summary>
        internal static string ProductInfo_Invalid_Vapor_Pressure {
            get {
                return ResourceManager.GetString("ProductInfo_Invalid_Vapor_Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vapor Pressure at C must be empty or &gt; 0.
        /// </summary>
        internal static string ProductInfo_Invalid_Vapor_Pressure_at_C {
            get {
                return ResourceManager.GetString("ProductInfo_Invalid_Vapor_Pressure_at_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save this {0} because validation errors exist..
        /// </summary>
        internal static string SelectableViewModel_Exception_Cannot_Save {
            get {
                return ResourceManager.GetString("SelectableViewModel_Exception_Cannot_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datamanagerservicesite/DataManager.svc.
        /// </summary>
        internal static string Server_DataManager_EndPoint {
            get {
                return ResourceManager.GetString("Server_DataManager_EndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 54.225.65.147.
        /// </summary>
        internal static string Server_IP {
            get {
                return ResourceManager.GetString("Server_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http:.
        /// </summary>
        internal static string Server_Transport {
            get {
                return ResourceManager.GetString("Server_Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A BodyPart must be chosen from the list..
        /// </summary>
        internal static string StaticItem_Invalid_BodyPart {
            get {
                return ResourceManager.GetString("StaticItem_Invalid_BodyPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Choice must be made from the list of valid options..
        /// </summary>
        internal static string StaticItem_Invalid_Choice {
            get {
                return ResourceManager.GetString("StaticItem_Invalid_Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A piece of Clothing suitable for the chose BodyPart must be chosen..
        /// </summary>
        internal static string StaticItem_Invalid_Clothing {
            get {
                return ResourceManager.GetString("StaticItem_Invalid_Clothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be provided, and be unique within this group..
        /// </summary>
        internal static string StaticItemModel_Invalid_Desc {
            get {
                return ResourceManager.GetString("StaticItemModel_Invalid_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be provided and unique within a Group..
        /// </summary>
        internal static string StaticItemModel_Invalid_Description {
            get {
                return ResourceManager.GetString("StaticItemModel_Invalid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid Group for Static Items..
        /// </summary>
        internal static string StaticItemModel_Invalid_GroupId {
            get {
                return ResourceManager.GetString("StaticItemModel_Invalid_GroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be unique within this group..
        /// </summary>
        internal static string StaticItemModel_Invalid_ItemId {
            get {
                return ResourceManager.GetString("StaticItemModel_Invalid_ItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid Group for Static Items..
        /// </summary>
        internal static string StaticTableModel_Invalid_Group {
            get {
                return ResourceManager.GetString("StaticTableModel_Invalid_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewer Id must be provided..
        /// </summary>
        internal static string Study_Reviewer_Id {
            get {
                return ResourceManager.GetString("Study_Reviewer_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study number must be present, and unique..
        /// </summary>
        internal static string Study_Study_Number {
            get {
                return ResourceManager.GetString("Study_Study_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Field Fortification.
        /// </summary>
        internal static string StudyViewModel_Command_Create_FieldFortification {
            get {
                return ResourceManager.GetString("StudyViewModel_Command_Create_FieldFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Monitoring Unit.
        /// </summary>
        internal static string StudyViewModel_Command_Create_MonitoringUnit {
            get {
                return ResourceManager.GetString("StudyViewModel_Command_Create_MonitoringUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected Field Fortifications.
        /// </summary>
        internal static string StudyViewModel_Command_Delete_Selected_FieldFortifications {
            get {
                return ResourceManager.GetString("StudyViewModel_Command_Delete_Selected_FieldFortifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected Monitoring Units.
        /// </summary>
        internal static string StudyViewModel_Command_Delete_Selected_MonitoringUnits {
            get {
                return ResourceManager.GetString("StudyViewModel_Command_Delete_Selected_MonitoringUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update this WorkerInfo because validation errors exist..
        /// </summary>
        internal static string WorkerInfo_Exception_Cannot_Update {
            get {
                return ResourceManager.GetString("WorkerInfo_Exception_Cannot_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age must be either empty, or between 10 and 127 (years).
        /// </summary>
        internal static string WorkerInfo_Invalid_Age {
            get {
                return ResourceManager.GetString("WorkerInfo_Invalid_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio Monitoring must either be empty, or a valid description.
        /// </summary>
        internal static string WorkerInfo_Invalid_Biomonitoring {
            get {
                return ResourceManager.GetString("WorkerInfo_Invalid_Biomonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Country.
        /// </summary>
        internal static string WorkerInfo_Invalid_Country {
            get {
                return ResourceManager.GetString("WorkerInfo_Invalid_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County / Locale must be either empty, or valid for the State or Province specified.
        /// </summary>
        internal static string WorkerInfo_Invalid_County_Locale {
            get {
                return ResourceManager.GetString("WorkerInfo_Invalid_County_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Employment.
        /// </summary>
        internal static string WorkerInfo_Invalid_Employment {
            get {
                return ResourceManager.GetString("WorkerInfo_Invalid_Employment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender must be either empty, or &quot;Male&quot;, or &quot;Female&quot;.
        /// </summary>
        internal static string WorkerInfo_Invalid_Gender {
            get {
                return ResourceManager.GetString("WorkerInfo_Invalid_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height must be either empty, or between {0} and {1} ({2}).
        /// </summary>
        internal static string WorkerInfo_Invalid_Height {
            get {
                return ResourceManager.GetString("WorkerInfo_Invalid_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WorkerId | ReplicateId pair must be unique within this Study..
        /// </summary>
        internal static string WorkerInfo_Invalid_Id {
            get {
                return ResourceManager.GetString("WorkerInfo_Invalid_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replicate Date must be provided.
        /// </summary>
        internal static string WorkerInfo_Invalid_Replicate_Date {
            get {
                return ResourceManager.GetString("WorkerInfo_Invalid_Replicate_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Season.
        /// </summary>
        internal static string WorkerInfo_Invalid_Season {
            get {
                return ResourceManager.GetString("WorkerInfo_Invalid_Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Site.
        /// </summary>
        internal static string WorkerInfo_Invalid_Site {
            get {
                return ResourceManager.GetString("WorkerInfo_Invalid_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State or Province must be either empty, or valid for the Country specified.
        /// </summary>
        internal static string WorkerInfo_Invalid_State_Province {
            get {
                return ResourceManager.GetString("WorkerInfo_Invalid_State_Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Task.
        /// </summary>
        internal static string WorkerInfo_Invalid_Task {
            get {
                return ResourceManager.GetString("WorkerInfo_Invalid_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town must be either empty, or valid for the county / locale specified.
        /// </summary>
        internal static string WorkerInfo_Invalid_Town {
            get {
                return ResourceManager.GetString("WorkerInfo_Invalid_Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight must be either empty, or between {0} and {1} ({2}).
        /// </summary>
        internal static string WorkerInfo_Invalid_Weight {
            get {
                return ResourceManager.GetString("WorkerInfo_Invalid_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years of Experience must be either empty, or a positive integer.
        /// </summary>
        internal static string WorkerInfo_Invalid_Years_Experience {
            get {
                return ResourceManager.GetString("WorkerInfo_Invalid_Years_Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker ID must be provided.
        /// </summary>
        internal static string WorkerInfo_Missing_Id {
            get {
                return ResourceManager.GetString("WorkerInfo_Missing_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replicate ID must be provided.
        /// </summary>
        internal static string WorkerInfo_Missing_Replicate_Id {
            get {
                return ResourceManager.GetString("WorkerInfo_Missing_Replicate_Id", resourceCulture);
            }
        }
    }
}
